const usersMock = {
  login: "CarinaNBP",
  id: 82219260,
  node_id: "MDQ6VXNlcjgyMjE5MjYw",
  avatar_url: "https://avatars.githubusercontent.com/u/82219260?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/CarinaNBP",
  html_url: "https://github.com/CarinaNBP",
  followers_url: "https://api.github.com/users/CarinaNBP/followers",
  following_url:
    "https://api.github.com/users/CarinaNBP/following{/other_user}",
  gists_url: "https://api.github.com/users/CarinaNBP/gists{/gist_id}",
  starred_url: "https://api.github.com/users/CarinaNBP/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/CarinaNBP/subscriptions",
  organizations_url: "https://api.github.com/users/CarinaNBP/orgs",
  repos_url: "https://api.github.com/users/CarinaNBP/repos",
  events_url: "https://api.github.com/users/CarinaNBP/events{/privacy}",
  received_events_url: "https://api.github.com/users/CarinaNBP/received_events",
  type: "User",
  site_admin: false,
  name: "Carina Nogueira & Carina Nogueira",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "Estudante de programação. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia in amet nulla, illum temporibus molestiae nam ducimus dolores. Voluptate unde velit dolores optio sequi corporis repellat, tempora quod ut animi?",
  twitter_username: null,
  public_repos: 15,
  public_gists: 0,
  followers: 6,
  following: 6,
  created_at: "2021-04-09T12:56:26Z",
  updated_at: "2021-08-10T13:37:06Z",
};

export default usersMock;
